os: linux
dist: xenial

language: python

python:
  - 3.8
  
install:
- pip install coveralls
- pip install pytest

script:
  - pytest keep
  - coverage run keep/test_keep.py pytest
  - coverage report -m
  
after_success:
- coveralls
