os: linux
dist: xenial

language: python

python:
  - 3.8
  
install:
- pip install codecov
- pip install pytest pytest-cov

script:
  - pytest --cov=keep --cov-report term-missing -v keep
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
