os: linux
dist: xenial

install:
- pip install -r requirements.txt
- pip install coveralls

script:
  - pytest keep
  - coverage run keep/test_keep.py pytest
  - coverage report -m
  
after_success:
- coveralls
